microsoft/fluentui-contrib

- package.json
- packages/nx-plugin/src/generators/library/findInstalledReactComponentsVersion.ts
- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/nx-plugin/src/generators/library/generator.ts
- yarn.lock
In order to guarantee that all new created packages will have a correct minimum supported peer dependency, package.json is autogenerated with the version installed in the current lockfile.
If authors need better backwards compatibility, they are responsible for testing the earlier versions of react-components themselves and setting the peer dependency manually.
> chore: Generate @fluentui/react-components peer dep safely

- change/@fluentui-contrib-react-shadow-ee5bd401-e23b-4c28-a3f8-dee02e2bca07.json
- packages/react-shadow/src/root.tsx
- packages/react-shadow/stories/root/Portals.stories.tsx
- packages/react-shadow/stories/root/index.stories.tsx
Adopts the change from https://github.com/microsoft/fluentui/pull/28395 and renders components powered by Portals in shadow roots.
> fix(react-shadow): render portals under shadow root

- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/nx-plugin/src/generators/library/generator.ts
- packages/react-chat/project.json
- packages/react-shadow/project.json
NX generated project.json does not include linting tsx files by default. Make this change for all current packages and update the library creation generator.
> chore: lint tsx files by default

- change/@fluentui-contrib-react-chat-f2407b1b-2a69-47b1-a19f-42c814cdf82a.json
- change/@fluentui-contrib-react-shadow-bc587195-24df-4bb0-8d55-669f797168d0.json
- packages/react-chat/package.json
- packages/react-shadow/package.json
Follow up for #20. Missed the version bump in the original PR.
> chore(react-shadow): require proper version of @fluentui/react-components

- .eslintrc.json
- change/@fluentui-contrib-react-chat-ac550fcf-0f5d-4b2f-8ab8-debddb6e589e.json
- package.json
- packages/nx-plugin/package.json
- packages/react-chat/package.json
- packages/react-chat/src/components/ChatMessage/ChatMessage.styles.ts
- packages/react-chat/src/components/ChatMessage/renderChatMessage.tsx
- packages/react-chat/src/components/ChatMessage/useChatMessage.ts
- packages/react-chat/src/components/utils/getDecorationIcon.tsx
- packages/react-chat/src/components/utils/mergeCallbacks.ts
- packages/react-chat/src/components/utils/useChatMessageFocusableGroup.ts
- packages/react-chat/src/components/utils/useChatMessagePopoverTrigger.ts
- packages/react-chat/src/components/utils/useEventCallback.ts
- packages/react-chat/stories/Chat/index.stories.tsx
- packages/react-chat/stories/ChatMessage/index.stories.tsx
- packages/react-chat/stories/ChatMyMessage/index.stories.tsx
- yarn.lock
Adds the
[no-extraneous-dependency](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-extraneous-dependencies.md) eslint rule so that there is a guarantee that all dependencies are declared in package.json.
Fixes the violations in react-chat and nx-plugin
> chore: Add extraneous dependency eslint rule

- change/@fluentui-contrib-react-chat-8a0422bd-aaaa-46d2-9962-006520348f61.json
- change/@fluentui-contrib-react-data-grid-react-window-7b037308-1547-49cc-9b5a-5ff9de12051f.json
- change/@fluentui-contrib-react-shadow-6ddd9824-b130-4001-ae67-3bff22314daf.json
- packages/nx-plugin/src/generators/library/files/.swcrc
- packages/react-chat/.swcrc
- packages/react-data-grid-react-window/.swcrc
- packages/react-shadow/.swcrc
Sets The compilation target of the repo to 2019 for webpack 4 compat webpack/webpack#10227 which does not support optional chaining without extra babel loader transpilation.
Also puts the repo in line with the Fluent UI core repo which uses es2019
> chore: Set compilation target to es2019

- packages/nx-plugin/src/executors/build/executor.ts
Updates build to include react-dom and types as peer dependencies to support [midgard-yarn-strict](https://github.com/VincentBailly/midgard-yarn-strict) which forces packages to declare all peer dependencies of their entire dependency tree.
This will also align peer dependencies with Fluent UI core repo.
> chore: Add react-dom to peer-dependencies with automation

- change/@fluentui-contrib-react-data-grid-react-window-792e435e-0385-4845-bd15-ee5909f20788.json
- packages/react-data-grid-react-window/src/components/DataGridBody/renderDataGridBody.tsx
The scope of this PR is to fix the direction for the virtualized DataGrid. Before adding this change, by default, react-window uses the default direction (which is `LTR` - check their [wiki page](https://react-window.vercel.app/#/api/FixedSizeGrid)), even if the FluentUI Provider set it to be `RTL`. It was fixed by passing the `direction` prop to `List` component. 
The changes were tested using Storybook and setting the `dir` parameter to `rtl`. You can check the changes in the following screenshots:
| Before  | After  |
|---|---|
| ![image](https://github.com/microsoft/fluentui-contrib/assets/43915731/8d536f57-6258-4a9d-a2de-e2900527c996)| ![image](https://github.com/microsoft/fluentui-contrib/assets/43915731/0465b428-0c90-4501-ab0b-915f816897af)  |
> [Virtualized DataGrid] Fix direction for List

- change/@fluentui-contrib-stylelint-plugin-2f2ebb22-17ec-474a-ba11-93127236e071.json
- packages/stylelint-plugin/src/rules/combinator-depth/README.md
- packages/stylelint-plugin/src/rules/combinator-depth/combinator-depth.test.ts
- packages/stylelint-plugin/src/rules/combinator-depth/combinator-depth.ts
It's valid to use these pseudoclasses to toggle visiblity or other changes in children elements.
> feat: :hover and :active pseudoclasses should not count to combinator depth

- .syncpackrc
- package.json
Peer dependencies are not actually installed by this repository and there is also no easy way to validate them with automation. #25 tried to implement some kind of validation for peer dependencies does not handle all cases correctly.
After this PR, it is up to library owners to make sure their libraries work correctly with the declared peer dependencies. https://github.com/microsoft/fluentui-contrib/issues/52 tracks adding automated validation
Allow mismatches in peer dependencies for `@fluentui/react-components` for now since it's the only known case currently where we _**want**_ mismatches
> chore: Allow peer dependency mismatches for @fluentui/react-components

- change/@fluentui-contrib-react-headless-provider-49dfe0a5-09f5-4d16-a4a9-f484382f4bcc.json
- packages/react-headless-provider/src/components/HeadlessFluentProvider/HeadlessFluentProvider.test.tsx
- packages/react-headless-provider/src/components/HeadlessFluentProvider/HeadlessFluentProvider.tsx
Fixes a warning from `@fluentui/react-utilities`:
```
@fluentui/react-utilities [assertSlots]:
"state.root" is not a slot!
Be sure to create slots properly by using "slot.always" or "slot.optional".
```
> fix(react-headless-provider): use functions required by JSX pragma

- change/@fluentui-contrib-react-shadow-50d448d8-13a6-4c02-b2a2-4054e6111b5f.json
- packages/react-shadow/src/root.tsx
This PR removes logic that does syncing of stylesheets as I don't see any condition when it should work and cannot reproduce when it's needed.
> fix(react-shadow): remove sync logic

- .github/workflows/ci.yml
Adds a `/stories` folder with `.gitkeep` file to avoid storybook build error. Also adds a new CI job to build affected storybook projects
> chore: fix docs deploy

- package.json
- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/react-tree-grid/package.json
- yarn.lock
The [TreeGrid implementation](https://github.com/microsoft/fluentui/pull/29780/files#diff-8749e1441ec3506af3496e403718146ffe051df15bbb62cafe19346ea8c253fd) provided by @adamsamec requires usage of the tabster version 5, which is already being used by latest v9 version (v9.44.4)
1. upgrade `@fluentui/react-components` to v9.44.4
> chore: update @fluentui/react-components version to latest

- change/@fluentui-contrib-react-resize-handle-fbab8534-342b-4a6e-8049-bcb49148efd3.json
- package.json
- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/react-resize-handle/package.json
- packages/react-tree-grid/package.json
- yarn.lock
1. Bumps `@fluentui/react-components` to 9.45.0 (the actual required release is 9.44.5 [Release](https://github.com/microsoft/fluentui/releases/tag/%40fluentui%2Freact-components_v9.44.5)), as https://github.com/microsoft/fluentui/pull/30322 is required by `react-tree-grid`
2. Bumps `@fluentui/react-utilities` to 9.16.0 ([Release](https://github.com/microsoft/fluentui/releases/tag/%40fluentui%2Freact-utilities_v9.16.0))
> chore: bumps `@fluentui/react-components` to  v9.45.0

- .eslintrc.json
- change/@fluentui-contrib-react-headless-provider-04ae5ded-4e21-4711-872b-dfd27f48e205.json
- package.json
- packages/react-draggable-dialog/src/index.ts
- packages/react-headless-provider/src/index.ts
- packages/react-tree-grid/src/index.ts
- yarn.lock
It's crucial to disallow usage of `export *` in barrel file that expose package public API.
this PR:
- adds `rnx-kit` eslint plugin version 0.4 in order to not create typescript-eslint package dupes
- enables API expansion rule as error violation ( dont worry it has autofix so just `nx run <project-name>:lint --fix`
- fixes violating packages
> chore: enable rnx-kit eslint plugin in order to enforce public API expansion at barrel files

- packages/react-tree-grid/package.json
- packages/react-tree-grid/src/components/TreeGridCell/useTreeGridCellStyles.styles.ts
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.tsx
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.types.ts
- packages/react-tree-grid/src/components/TreeGridRowGroup/TreGridRow.types.ts
- packages/react-tree-grid/src/components/TreeGridRowGroup/TreeGridRowGroup.tsx
- packages/react-tree-grid/src/components/TreeGridRowGroup/index.ts
- packages/react-tree-grid/src/index.ts
- packages/react-tree-grid/stories/Default.stories.tsx
1. Introduces `TreeGridRowGroup` component
1. there's nothing limiting the user to add more than one `groupOwner` in the same group
2. there's nothing limiting that the first row on a `TreeGridRowGroup` should be the `groupOwner`
3. each `TreeGridRow` controls it's own visibility (this might not be ideal for virtualization cases, as the visibility of the nodes is dictated by the virtualization library on scroll normally?!)
> feat(react-tree-grid): implements TreeGridRowGroup component

- .vscode/extensions.json
- nx.json
- package.json
- packages/nx-plugin/src/executors/playwright/executor.ts
- packages/nx-plugin/src/executors/playwright/schema.d.ts
- packages/nx-plugin/src/executors/playwright/schema.json
- packages/nx-plugin/src/generators/playwright-component-configuration/files/playwright.config.ts.template
- packages/nx-plugin/src/generators/playwright-component-configuration/generator.spec.ts
- packages/nx-plugin/src/generators/playwright-component-configuration/generator.ts
- yarn.lock
**Before:**
our custom playwright executor wasn't working before.
**After:**
After detailed analysis of core nx/playwright plugin I realized that there are various additional gymnastics that need to happen which goes beyond simple `execSync` call.
Most of the implementation was copied from nx/playwright with our custom API modification + pointing to proper CLI for component test.
Last but not least CI needs to install playwright browsers so our executor will now handle this behind the scenes.
Generator was tweaked to incorporate new target changes including eslint setup to follow playwright best practices
Follows https://github.com/microsoft/fluentui-contrib/pull/95
> feat(nx-plugin): redo playwright executor/generator setup to accept all nx flags and make it work

- packages/react-tree-grid/.storybook/preview.tsx
1. Adds `role="application"` on decorator to avoid issues with JAWS, seems like treegrid examples have to be wrapped around `role="application"`
> chore(react-tree-grid): add role="application" on decorator

- change/@fluentui-contrib-react-data-grid-react-window-grid-746c1842-7b7b-4440-9d26-b7bcb5babe31.json
- packages/react-data-grid-react-window-grid/README.md
- packages/react-data-grid-react-window-grid/src/components/DataGrid/renderDataGrid.tsx
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/renderDataGridBody.tsx
- packages/react-data-grid-react-window-grid/src/components/DataGridHeaderRow/DataGridHeaderRow.types.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridHeaderRow/renderDataGridHeaderRow.tsx
- packages/react-data-grid-react-window-grid/src/contexts/bodyRefContext.ts
- packages/react-data-grid-react-window-grid/src/contexts/headerListRefContext.ts
- packages/react-data-grid-react-window-grid/stories/DataGrid/VirtualizedDataGrid.stories.tsx
use [VaraiableSizeGrid](https://react-window.vercel.app/#/examples/grid/variable-size) for body and [VariableSizeList](https://react-window.vercel.app/#/examples/list/variable-size) for header to make users of the grid in react-data-grid-react-window-grid have the ability for different column size of each column.
> feat(react-data-grid-react-window-grid): use VaraiableSizeGrid for body and VariableSizeList for header

- packages/react-draggable-dialog/src/components/DraggableDialog/DraggableDialog.tsx
- packages/react-draggable-dialog/src/components/DraggableDialog/DraggableDialog.types.ts
- packages/react-draggable-dialog/src/components/DraggableDialog/useDraggableDialog.ts
- packages/react-draggable-dialog/src/components/DraggableDialogHandle/DraggableDialogHandle.tsx
- packages/react-draggable-dialog/src/components/DraggableDialogHandle/DraggableDialogHandle.types.ts
- packages/react-draggable-dialog/src/components/DraggableDialogHandle/useDraggableDialogHandle.ts
- packages/react-draggable-dialog/src/components/DraggableDialogSurface/DraggableDialogSurface.tsx
- packages/react-draggable-dialog/src/components/DraggableDialogSurface/DraggableDialogSurface.types.ts
- packages/react-draggable-dialog/src/components/DraggableDialogSurface/useDraggableDialogSurface.ts
- packages/react-draggable-dialog/src/contexts/DraggableDialogContext.ts
This PR doesn't add any logic but splits the component into separate state hooks.
This change is needed to make it easy to test the state that goes into the components. Some components are renderless, which makes it impossible to test the state integrity without this change.
> feat(react-draggable-dialog): split component logic into separate hooks

- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.spec.tsx
- packages/react-tree-grid/src/components/TreeGridCell/TreeGridCell.tsx
- packages/react-tree-grid/stories/Default.stories.tsx
- packages/react-tree-grid/stories/EmailInbox.stories.tsx
- packages/react-tree-grid/stories/Meet.stories.tsx
1. Fix wrong `role` on header `TreeGridCell`
2. updates stories to be more accessible
> bugfix(react-tree-grid): header TreeGridCell should have role rowheader instead of columnheader

- packages/react-tree-grid/stories/Meet.stories.tsx
Solves a11y issues on Meet stories by providing proper `aria-label` to rows and the row header
> chore(react-tree-grid): resolve Meet stories a11y issues

- packages/react-tree-grid/stories/Meet.stories.tsx
Modifies Meet story to be more accessible
1. adds `aria-label` to the rowheader cell instead of the row
2. add `aria-description` to the row, providing extra information
3. add simpler `aria-label` to the header button
> chore(react-tree-grid): follow up on a11y issue for Meet stories

- change/@fluentui-contrib-houdini-utils-09b68852-bed9-4483-9f6c-f11a7abdb080.json
- packages/houdini-utils/CHANGELOG.json
- packages/houdini-utils/CHANGELOG.md
- packages/houdini-utils/package.json
- packages/houdini-utils/src/index.ts
- packages/houdini-utils/src/paint/fallback/animate.ts
- packages/houdini-utils/src/paint/fallback/anims/play.ts
- packages/houdini-utils/src/paint/fallback/fallbackPaintAnimation.ts
- packages/houdini-utils/src/paint/fallback/keyframe.ts
- packages/houdini-utils/src/types.ts
- packages/houdini-utils/stories/Utils/Fallback.stories.tsx
- packages/houdini-utils/stories/Utils/FallbackWithDuration.stories.tsx
- packages/houdini-utils/stories/Utils/index.stories.tsx
Ths user will no longer need to provide a stopping condition. The fallback animation now returns its own imperative `stop` function
```ts
const animation = fallbackPaintAnimation({...options, isStopped: ()  => false});
const { id, play, canvas, cleanup } = animation(node);
let stopCondition = false;
const isStopped = () => stopCondition === true;
play(onComplete, isStopped, onUpdate);
const stop = () => stopCondition = true;
// stops the animation
stop();
```
```ts
const animation = fallbackPaintAnimation({...options});
const { id, play, stop, canvas, cleanup } = animation(node);
play(onComplete, onUpdate);
// stops the animation
stop();
```
> BREAKING: Stopping a fallback animation should be imperative

- change/@fluentui-contrib-houdini-utils-f257be28-ff99-4755-a95e-f22fef91a1db.json
- packages/houdini-utils/src/paint/fallback/anims/play.ts
- packages/houdini-utils/src/types.ts
- packages/houdini-utils/stories/Utils/Fallback.stories.tsx
- packages/houdini-utils/stories/Utils/FallbackWithDuration.stories.tsx
Background images are now handled internally - this is no longer necessary in userland. However `onUpdate` can still be used for custom user handling
The follow properties in the options of `fallbackPaintAnimation` were redundant:
* `target - this was the first argument of `fallbackPaintAnimation`
* `onComplete` - this can be set in the `play` function
* `onUpdate` - this can be set in the `play` function
> BREAKING: Remove unnecessary API and handle fallback image internally

- change/@fluentui-contrib-houdini-utils-117ef41d-ff9b-42d8-a858-02d3dbda566d.json
- packages/houdini-utils/src/paint/fallback/animate.ts
Iterations were tracked  with 0 indexing which resulted in a bug since iteration counts are defined with 1 indexing numbers.
> fix: iterations should be tracked with 1 indexing

- change/@fluentui-contrib-react-data-grid-react-window-grid-6e4cc41f-2239-4863-b583-e9c7ef52d150.json
- packages/react-data-grid-react-window-grid/src/components/DataGrid/DataGrid.tsx
- packages/react-data-grid-react-window-grid/src/components/DataGrid/DataGrid.types.ts
- packages/react-data-grid-react-window-grid/src/components/DataGrid/index.ts
- packages/react-data-grid-react-window-grid/src/components/DataGrid/renderDataGrid.tsx
- packages/react-data-grid-react-window-grid/src/components/DataGrid/useDataGrid.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-data-grid-react-window-grid/src/index.ts
- packages/react-data-grid-react-window-grid/stories/DataGrid/VirtualizedDataGrid.stories.tsx
Fix issue #141, There is cache from 'react-window' for performance improvement reason. here is the doc how to force update:
> `resetAfterColumnIndex(index: number, shouldForceUpdate: boolean = true): void`
> VariableSizeGrid caches offsets and measurements for each column index for performance purposes. This method clears that 
> cached data for all columns after (and including) the specified index. It should be called whenever a column's width changes. (Note that this is not a typical occurrance.)
>
> By default the grid will automatically re-render after the index is reset. If you would like to delay this re-render until e.g. a state update has completed in the parent component, specify a value off false for the second, optional parameter.
Before fix the bug behaves:
After fix:
> minor(react-data-grid-react-window-grid): bug fix on columnWidth not been called when rerendered

- change/@fluentui-contrib-react-data-grid-react-window-grid-d4508d9e-d1fb-4f71-b424-72cde2b05aef.json
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/index.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/renderDataGridBody.tsx
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/useDataGridBodyStyles.styles.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridHeaderRow/index.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridHeaderRow/renderDataGridHeaderRow.tsx
- packages/react-data-grid-react-window-grid/src/index.ts
We have some requirements that need to add custom styles to the react-window Grid/List components in DataGrid. Add classname for those component so we can use CSS selector to add custom styles.
> minor: add classname for react-window component to support styling by selector

- packages/nx-plugin/src/generators/configure-storybook/generator.spec.ts
- packages/nx-plugin/src/generators/configure-storybook/generator.ts
Updates nx-plugin:configure-storybook generator to not include bolierplate config that is invalid for us/not necessary
Fixes: https://github.com/microsoft/fluentui-contrib/pull/145#discussion_r1534734704
> fix(nx-plugin): opt out from nx SB configurationGenerator boilerplate which is invalid/unnecessary for us

- packages/nx-plugin/src/generators/component/files/stories/__componentName__/index.stories.tsx.template
- packages/nx-plugin/src/generators/component/generator.ts
When following the [contributing guidelines](https://github.com/microsoft/fluentui-contrib/blob/main/CONTRIBUTING.md#creating-a-new-package) a freshly scaffolded package would not pass the build.
Generator templates have been updated so a freshly minted package passes the build.
> fix(nx-plugin): make `component` generator result pass ci checks

- change/@fluentui-contrib-react-draggable-dialog-a0f3a781-ab7a-42d4-ae63-695043256bbc.json
- packages/react-draggable-dialog/package.json
Remove the private flag from package to enable the release of the Draggable Dialog
> feat(react-draggable-dialog): prepare for first release

- jest.preset.js
- package.json
- packages/nx-plugin/.swcrc
- packages/nx-plugin/jest.config.ts
- packages/nx-plugin/src/generators/configure-storybook/generator.spec.ts
- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/nx-plugin/src/generators/library/generator.ts
- yarn.lock
we use swc for jest transpilation in all packages except nx-plugin. 
this PR unifies this / also makes the execution bit faster -> `~0.5s faster`
- transform overrides were necessary because nx presets specifies ts-jest by default
- nx-plugin#library generator overrides to not add `ts-jest` on invocation
- removes ts-jest dependency
> chore: use swc instead ts-jest in whole monorepo for jest

- packages/react-data-grid-react-window/stories/DataGrid/VirtualizedDataGrid.stories.tsx
Updates the virtualized data grid example to use `focusMode="group"` for cells since there can be nested buttons inside.
> docs: Use `group` focusMode for cells

- change/@fluentui-contrib-react-tree-grid-80881ec7-8cac-46fe-9082-cf87ab48dbeb.json
- packages/react-tree-grid/stories/Calls.stories.tsx
- packages/react-tree-grid/stories/Docs.mdx
- packages/react-tree-grid/stories/index.stories.tsx
Adds example similar to the behavior of the Calls app in Teams.
The Calls app has a collapsible History panel that contains every call. Each call once hovered presents 2 new actions.
I this simplified example, we used the TreeGrid to simulate a similar behaviour but without removing content
> docs(react-tree-grid): adds Calls example (contextual menu + hidden menu)

- .eslintrc.json
- change/@fluentui-contrib-houdini-utils-cd0078ba-b3bb-463a-b1b3-41674707f809.json
- packages/houdini-utils/src/paint/fallback/animate.ts
- packages/houdini-utils/src/paint/fallback/anims/play.ts
- packages/houdini-utils/src/paint/fallback/fallbackPaintAnimation.ts
- packages/houdini-utils/src/paint/fallback/keyframe.ts
- packages/houdini-utils/src/paint/fallback/util/canvas.ts
- packages/houdini-utils/src/paint/fallback/util/wrapper.ts
- packages/houdini-utils/src/util/featureDetect.ts
- packages/houdini-utils/stories/Utils/index.stories.tsx
- packages/react-themeless-provider/stories/ThemelessFluentProvider/Default.stories.tsx
- packages/react-tree-grid/stories/EmailInbox.stories.tsx
- packages/react-tree-grid/stories/Meet.stories.tsx
- packages/react-tree-grid/stories/Virtualization.stories.tsx
Accessing global objects can cause problems in multi-window applications because we may be accessing a global object in the wrong `window` context. 
This change enables the `eslint` `no-restricted-globals` rule to disallow global access.
For more details see the corresponding PR in Fluent UI: https://github.com/microsoft/fluentui/pull/30967
This change does not address problems in `houdini-utils` specifically as those will be addressed separately.
> chore: update eslint to disallow globals

- change/@fluentui-contrib-react-draggable-dialog-9a965112-4f42-4d8b-834e-08364ccdaab5.json
- packages/react-draggable-dialog/src/components/DraggableDialogSurface/DraggableDialogSurface.tsx
- packages/react-draggable-dialog/src/components/DraggableDialogSurface/useDraggableDialogSurface.ts
In the newest released version of Fluent UI 9, the DialogSurface component must support ref forwarding. If DialogSurface is wrapped inside another component, then that component must support ref forwarding. See e.g. https://github.com/microsoft/fluentui/issues/31630
That is the case in this module, react-draggable-dialog. DraggableDialogSurface is a wrapper around DialogSurface. If using this module with the newest Fluent UI 9 build, it throws the following error: 
```
Error: @fluentui/react-motion: Invalid child element.
Motion factories require a single child element to be passed. That element element should support ref forwarding i.e. it should be either an intrinsic element (e.g. div) or a component that uses React.forwardRef().
```
This pull request adds the necessary forwarded ref …
> feat(react-draggable-dialog): add ref forwarding for DraggableDialogSurface

- change/@fluentui-contrib-react-data-grid-react-window-9616c1ea-7098-4f93-bf9e-898a71ff92d1.json
- change/@fluentui-contrib-react-data-grid-react-window-grid-256637a5-2062-4d52-b56c-da5093435110.json
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/useDataGridBody.tsx
- packages/react-data-grid-react-window-grid/stories/DataGrid/DataGridScrollingIndicators.stories.tsx
- packages/react-data-grid-react-window-grid/stories/DataGrid/index.stories.tsx
- packages/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-data-grid-react-window/src/components/DataGridBody/useDataGridBody.tsx
- packages/react-data-grid-react-window/stories/DataGrid/DataGridScrollingIndicators.stories.tsx
- packages/react-data-grid-react-window/stories/DataGrid/index.stories.tsx
If your component's items are expensive to render, you can boost performance by rendering a placeholder while the user is scrolling. To do this, add the `useIsScrolling` property to your List or Grid. Now an additional parameter, `isScrolling`, will be passed to your render method.
Original doc from `react-window` https://react-window.vercel.app/#/examples/list/scrolling-indicators).vercel.app/#/examples/list/scrolling-indicators
> feat(react-data-grid-react-window*): add scrolling indicators

- change/@fluentui-contrib-react-chat-92014f96-b0d6-45d4-a231-f0c2843bcc96.json
- packages/react-chat/src/components/Chat/Chat.test.tsx
- packages/react-chat/src/components/Chat/useChat.ts
Allows tabster attributes to be overriden and adds a test to prevent regression
> fix: Chat should be able to override tabster attributes

- .gitignore
- change/@fluentui-contrib-azure-theme-38aa95aa-6904-46a0-a2d1-262a63424cab.json
- change/@fluentui-contrib-azure-theme-50ec81f2-7b56-4409-ba3e-74f8e5767a9c.json
- package.json
- packages/azure-theme/package.json
- yarn.lock
**Repo:**
- update gitignore https://github.com/microsoft/fluentui-contrib/pull/190#discussion_r1686713024
- add `react-icons` to repo deps to avoid transitive dep usage 
**azure-theme:**
- move react-icons to peerDependencies to avoid dupes in user land which lead to huge perf hits (https://github.com/microsoft/fluentui/issues/31714#issuecomment-2192050491)
- setup beachball to allow only change types that mirror package zero versioned semver policy
- 0.x.x
- `type: patch` == FIXes and FEATures 0.x.<b>X</b>
- `type: minor` == BREAKING change  0.<b>X</b>.x
- follows https://github.com/microsoft/fluentui-contrib/pull/190#discussion_r1686713024 and https://github.com/microsoft/fluentui-contrib/pull/203
> chore: add react-icons to repo deps to avoid transitive dependency usage from react-components, tweak azure-theme dependencies

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- jest.preset.js
- removes redundant `docs` job from PR pipeline
- migratest to latest https://github.com/nrwl/nx-set-shas
- uses env variables to set NX common CLI args
- uses same jest setup as in core https://github.com/microsoft/fluentui/pull/32096 ( although there seems to be no perf gains because GHA runs on weak machine )
> ci: simplify pipelines and setup jest to follow fluent core setup

- change/@fluentui-contrib-react-tree-grid-7314d4c2-4f6d-4d2d-a3b3-aefea024d9c0.json
- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.tsx
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.tsx
Fixes https://github.com/microsoft/fluentui-contrib/issues/210
1. Ensures that `props` will always overrides internal attributes (exception is event handlers, where the internal and external are merged to ensure behaviour)
> bugfix: allow override internal attributes through props

- change/@fluentui-contrib-react-tree-grid-c4eb3274-5637-442a-850a-f7c704e25d82.json
- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.tsx
- packages/react-tree-grid/src/components/TreeGridInteraction/TreeGridInteraction.tsx
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.tsx
Fixes bug introduced by https://github.com/microsoft/fluentui-contrib/pull/211
In https://github.com/microsoft/fluentui-contrib/pull/211 we started overriding internal tabster attributes by the ones provided by `props`. This may cause behavioral issue due to `props` removing internal necessary tabster attributes.
This PR fixes this by using `useMergedTabsterAttributes` to merge internal attributes with `props` one instead of replacing
> bugfix(react-tree-grid): merges tabster attributes instead of replacing with props

- change/@fluentui-contrib-react-resize-handle-9a67b6d5-5968-4c4a-806a-cf1d5cd12ca4.json
- packages/react-resize-handle/src/hooks/useResizeHandle.component-browser-spec.tsx
- packages/react-resize-handle/src/hooks/useResizeHandle.ts
- packages/react-resize-handle/src/hooks/useResizeHandleExample.component-browser-spec.tsx
- Reverts usage of `useEventCallback()` (see #214) as `useEventCallback()` can't be used inside refs
- Adds a basic test to ensure that callbacks work
> fix(resize-handle): restore to useCallback, add tests

- change/@fluentui-contrib-react-resize-handle-8d62436f-d3a1-4246-8e9e-57eecc1d5de2.json
- packages/react-resize-handle/src/hooks/useResizeHandle.component-browser-spec.tsx
- packages/react-resize-handle/src/hooks/useResizeHandle.ts
- packages/react-resize-handle/src/hooks/useResizeHandleExample.component-browser-spec.tsx
After doing research about the support of `separator` and `slider` roles across different screen readers and platforms it became obvious that the slider role has much better narration and keyboard support.
While `separator` fits the use case the best on paper, in real-world it's support leaves much to be desired.
To summarize the issues with `separator`:
- aria-label not supported on VoiceOver on Mac for `separator`
- VO keys not working for `separator`
- current value (aria-valuetext) not being narrated in Jaws
- no mode auto switching in NVDA and Jaws, hindering the experience.
All of these issues are avoided by using `slider`.
"Horizontal" and "vertical" orientation needs to be flipped for "slider".
> feat(react-resize-handle): Use slider role for better screen reader support

- .github/CODEOWNERS
- package.json
- tools/scripts/preinstall.mjs
- tools/scripts/verify-repo-integrity.mjs
this repo is an integrated nx repo (https://nx.dev/concepts/integrated-vs-package-based), thus there is no need for hoisting and other workspace package manager related jazz.
In the recent past few contributors added yarn.lock by accident as we didnt have any validation/automation for that.
This PR adds new verification to our verify repo integrity script to mitigate invalid yarn.lock additions.
**Demo:** 
all good:
failing:
- https://github.com/microsoft/fluentui-contrib/pull/224
- https://github.com/microsoft/fluentui-contrib/pull/202/files/01a351e64b5e1c551818d718a9c749cde8fb6a39#diff-44c004bf424fe7b2b154315253e520db3c5126aa009bfe6f02a3996db1c1f10d
> feat(tools): add yarn.lock verification to repo integrity script

- change/@fluentui-contrib-variant-theme-5f415918-9549-4242-a32a-3fc71e85c865.json
generate change file in order to trigger first release
- command used: `yarn change --force -p @fluentui-contrib/variant-theme`
- change type: `patch` . why? we are using zero based semver `0.m.p` / p=patch (features/fixes) m=minor (breaking change)
> feat(variant-theme): prepare initial release

- apps/docsite/project.json
- change/@fluentui-contrib-react-keytips-3771f4cd-49f4-48ff-a40a-30cb83e0610f.json
- packages/nx-plugin/src/generators/component/files/stories/__componentName__/index.stories.tsx.template
- packages/nx-plugin/src/generators/component/generator.spec.ts
- packages/react-keytips/stories/index.stories.ts
1. Remove the unnecessary `docs` property from `apps/docsite/project.json`. 
2. For package stories titles, adopt the `Packages/` format to ensure a consistent structure on the docsite. 
3. Modify the nx-plugin storybook generator to utilize the template for story titles.
**Before:**
**After**:
> fix: add prefix to packages story titles

- change/@fluentui-contrib-react-keytips-a837d56c-a0f7-4c82-a6e8-4acb794f4fc7.json
- packages/react-keytips/src/Keytip.ts
- packages/react-keytips/src/Keytips.ts
- packages/react-keytips/src/index.ts
- packages/react-keytips/stories/Default.stories.tsx
- packages/react-keytips/stories/Dynamic.stories.tsx
- packages/react-keytips/stories/WithTabs.stories.tsx
- packages/react-keytips/stories/index.stories.tsx
Currently, the Keytips implementation on our documentation site isn’t working optimally because each story contains its own instance of the Keytips component. This setup was manageable when the components were only separated in stories, but it’s not effective for the docsite. Ideally, the Keytips component should be added once at the application level. With the current configuration, we would end up registering four different handlers.
> docs(react-keytips): improve keytips for docsite

- change/@fluentui-contrib-react-interactive-tab-8aa8ba4d-13ec-4ea7-b62f-55b5e8d76951.json
- packages/react-interactive-tab/src/index.ts
barrel file for InteractiveTab should export all types and hooks, in addition to the component
> refactor(react-interactive-tab): export all types and hooks from barrel file

- change/@fluentui-contrib-react-keytips-5580747c-3c9f-4750-9854-00b3d534e82b.json
- packages/react-keytips/package.json
- packages/react-keytips/src/components/Keytip/Keytip.types.ts
- packages/react-keytips/src/components/Keytips/Keytips.component-browser-spec.tsx
- packages/react-keytips/src/components/Keytips/Keytips.types.ts
- packages/react-keytips/src/components/Keytips/KeytipsExamples.component-browser-spec.tsx
- packages/react-keytips/src/components/Keytips/useKeytips.tsx
- packages/react-keytips/src/components/Keytips/useKeytipsState.ts
- packages/react-keytips/src/utilities/index.ts
- packages/react-keytips/src/utilities/isDisabled.ts
- packages/react-keytips/src/utilities/isTargetVisible.ts
- packages/react-keytips/stories/Default.stories.tsx
- packages/react-keytips/stories/OverflowMenu.stories.tsx
According to design spec, keytips should not be shown for disabled targets
> fix(react-keytips): do not show keytips for disabled targets

- packages/react-tree-grid/stories/LiveMeetingsList.stories.tsx
- packages/react-tree-grid/stories/index.stories.tsx
Adds an example to `TreeGrid` stories on how to setup a list. Based on [Meets](https://microsoft.github.io/fluentui-contrib/react-tree-grid/?path=/story/packages-react-tree-grid--meet) example
> doc(react-tree-grid): adds story with example of a TreeGrid as a list

- change/@fluentui-contrib-variant-theme-30b11b3b-d257-4605-a5e0-3b645353268b.json
- packages/variant-theme/src/ThemeGenerator.ts
Since color is user's choice, so we will keep the color, and do not flip it when it has contrast issue.
before:
after:
> feat(variant-theme): keep custom colors

- change/@fluentui-contrib-react-keytips-0d1d16b6-84a2-42c8-88eb-2076c577056f.json
- packages/react-keytips/src/components/Keytips/useKeytips.tsx
- packages/react-keytips/src/hooks/useKeytipRef.ts
- packages/react-keytips/stories/OverflowMenu.stories.tsx
`useKeytips` hook was not removing alias node, plus it had duplicates and it showed them  in some cases (see Overflow example below).
**Before:** 
https://github.com/user-attachments/assets/2b48e1c1-5dd8-48c1-b17b-a90c7931554e
**After:** 
https://github.com/user-attachments/assets/a94c20c3-ec1b-4c07-9e70-e1f307f03372
> fix(react-keytips): fix tree issue with not removing the nodes

- change/@fluentui-contrib-stylelint-plugin-79aafcea-5765-4f2c-af35-91dba0eb16de.json
- packages/stylelint-plugin/src/rules/combinator-depth/combinator-depth.test.ts
- packages/stylelint-plugin/src/rules/combinator-depth/combinator-depth.ts
Adds a check for the tokenizedSelector length before checking further indexes in the tokenized selector array.
Adds tests to cover the regression
> fix: Add null guard for depth check

- .eslintrc.json
- packages/nx-plugin/.eslintrc.json
- packages/nx-plugin/package.json
- packages/nx-plugin/project.json
- packages/nx-plugin/src/utils.ts
Introduce https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks which will become primary source of truth of depedencies specifications within fluent packages, which will be crucial for Nx Release migration.
This PR enables the rule on internal nx-plugin for better testing.
Relates to https://github.com/microsoft/fluentui-contrib/pull/281
> lint: setup nx dependency-checks rule

- nx.json
Adds production configuration for Nx Release Plans and publishing.
> see https://nx.dev/recipes/nx-release/file-based-versioning-version-plans#file-based-versioning-version-plans
Relates to https://github.com/microsoft/fluentui-contrib/pull/281
> chore: setup nx release with version plans

- azure-pipelines.yml
Leverages ADO github app connection instead using PAT for pushing back on release trigger
> ci: remove use of PAT on release pipeline

- change/@fluentui-contrib-react-keytips-d123b6a8-376c-449e-a0b1-9698b5da6667.json
- packages/react-keytips/src/utilities/isTargetVisible.ts
- packages/react-keytips/stories/Overflow/OverflowMenu.tsx
- packages/react-keytips/stories/Shortcuts.stories.tsx
**Before:**
**After:**
In the Overflow example, the overflowed element stays in the DOM after it’s overflowed. Just checking the visibility or display styles isn’t enough. For example, with a Keytip attached to a SplitButton, the styles were applied to the root div of the SplitButton, not the specific side button where the Keytip was attached. To make this more reliable, we could add a check for the data-overflowing attribute.
> fix(react-keytips): do not show overflowing keytips

- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/nx-plugin/src/generators/library/generator.ts
- packages/react-interactive-tab/project.json
- packages/react-keytips/project.json
Since Nx Release was implemented within nx core `@nx/js:library` generator started to add nx release related setup that is not aligned with our specific needs.
**This PR:**
- normalizes existing project configs
- mitigates aforementioned issue in our library generator
> fix(nx-plugin): remove unwanted @nx/js release boilerplate from library generator output

- change/@fluentui-contrib-react-keytips-eee8961e-66d4-46b7-98a1-4e0f0c7b66bc.json
- packages/react-keytips/README.md
- packages/react-keytips/src/components/Keytip/Keytip.types.ts
- packages/react-keytips/src/components/Keytips/Keytips.component-browser-spec.tsx
- packages/react-keytips/src/components/Keytips/Keytips.types.ts
- packages/react-keytips/src/docs/MIGRATION.md
- packages/react-keytips/src/docs/Spec.md
- packages/react-keytips/src/hooks/useHotkeys.test.ts
- packages/react-keytips/src/hooks/useHotkeys.ts
fixed the issue with modifiers and adding control as a modifier. Updated README.
> fix(react-keytips): allow multiple modifiers

- change/@fluentui-contrib-react-keytips-050264dc-fc06-4619-bc99-d97fced79a69.json
- packages/react-keytips/README.md
- packages/react-keytips/src/components/Keytips/Keytips.types.ts
- packages/react-keytips/src/docs/Spec.md
I was unclear on the hotkey to display `KeyTips` so I've updated the docs to:
1. Explicitly call out the default Windows and macOS hotkeys in the props table
2. Remove a period from the default value in the props table. This made me think the key sequence was `alt + meta + .`
> Clarifies `startSequence` in `KeyTips` docs

- packages/teams-components/jest.config.ts
- packages/teams-components/src/components/Button/Button.test.tsx
- packages/teams-components/src/components/Button/Button.tsx
- packages/teams-components/src/components/Button/index.ts
- packages/teams-components/src/components/Button/validateIconButton.ts
- packages/teams-components/src/components/Button/validateProps.ts
- packages/teams-components/src/components/MenuButton/MenuButton.styles.ts
- packages/teams-components/src/components/MenuButton/MenuButton.test.tsx
- packages/teams-components/src/components/MenuButton/MenuButton.tsx
- packages/teams-components/src/components/MenuButton/index.ts
- packages/teams-components/src/components/ToggleButton/ToggleButton.test.tsx
- packages/teams-components/src/components/ToggleButton/ToggleButton.tsx
- packages/teams-components/src/components/ToggleButton/index.ts
- packages/teams-components/src/index.ts
- packages/teams-components/src/strictSlot.ts
- packages/teams-components/stories/Button/Default.stories.tsx
- packages/teams-components/stories/Button/index.stories.tsx
- packages/teams-components/stories/MenuButton/Default.stories.tsx
- packages/teams-components/stories/MenuButton/index.stories.tsx
- packages/teams-components/stories/ToggleButton/Default.stories.tsx
- packages/teams-components/stories/ToggleButton/index.stories.tsx
Adds strict API for Button, ToggleButton, MenuButton components that:
* restricts appearance
* supports and enforces tooltip for icon buttons
* enforces strics CSS classes
* supports strict icon and toltip slots with lightweight types that are compatible with Fluent UI slots
> feat: Add Button components for teams-components package

- packages/teams-components/src/components/Button/Button.tsx
- packages/teams-components/src/strictStyles/index.ts
- packages/teams-components/src/strictStyles/types.ts
- packages/teams-components/src/strictStyles/validateStrictClasses.ts
Updates strict styles API to support component level extensions by leveraging generics throughout all the types. Example of usage
```tsx
const useStrictStyles = makeStrictStyles<typeof Button>({
strict: {
alignSelf: 'center',
// 👇 `maxWidth` only exists when Button style extensions are used
maxWidth: '100%',
},
});
// 👇 This is equally valid usage for the `Button` component without enabling component styling extensions
const useStrictStyles = makeStrictStyles({
strict: {
alignSelf: 'center',
},
});
<Button className={strictStyles.strict}>Button</Button>
```
> feat: Extensions to makeStrictStyles

- .github/workflows/docs.yml
Failed job: https://github.com/microsoft/fluentui-contrib/actions/runs/13457302489 
`actions/upload-artifact: v3` is [no longer accessible for usage](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). 
Upload to the latest [upload-page-artifact](https://github.com/actions/upload-pages-artifact) should solve it: https://github.com/actions/upload-pages-artifact/blob/main/action.yml#L80
> chore(ci): update github pages upload action

- change/@fluentui-contrib-react-resize-handle-e309274a-7736-463b-91db-fd3709a9b435.json
- packages/react-resize-handle/src/hooks/useMouseHandler.ts
- packages/react-resize-handle/src/hooks/useResizeHandle.component-browser-spec.tsx
- packages/react-resize-handle/src/hooks/useResizeHandle.test.tsx
- packages/react-resize-handle/src/hooks/useResizeHandleExample.component-browser-spec.tsx
This PR changes the order of events dispatch in the `resize-handle` component. 
- There was a `requestAnimationFrame` that could scheduled multiple times (via `mousemove` event) as it gets never cancelled
- `onChange` is dispatched by `rAF` so it always happened after `onDragEnd` (`mouseup` event) that was not expected
- `requestAnimationFrame` calls don't collide
- if `onDragEnd` (`mouseup` event) is dispatched, we will cancel current `rAF` (from `mousemove` event) and invoke `onChange` immediately so it will happen **before** `onDragEnd`
- Browser tests updated (also fixed types issues)
- Unit tests added for this specific scenario
> fix(resize-handle): update events dispatch order

- change/@fluentui-contrib-houdini-utils-7e3da416-5d7a-454d-b0e0-32ca2c6fcbf0.json
- packages/houdini-utils/src/paint/fallback/fallbackPaintAnimation.ts
- packages/houdini-utils/src/util/featureDetect.ts
This PR adds a more robust DOM-feature detect function and it further adds another check before a code path that makes significant use of DOM APIs.
A partner team reported the following error:
```
Server Error
ReferenceError: document is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
hasWebkitCanvas
```
This is from a NextJS app and we established the issue was Next SSRing a Houdini component.
> More robust SSR check for `houdini-utils`

- change/@fluentui-contrib-react-tree-grid-23f7ff6f-2457-4944-bb7f-a1f273d876be.json
- packages/react-tree-grid/package.json
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.tsx
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.types.ts
- packages/react-tree-grid/src/components/TreeGridRowTrigger/TreeGridRowTrigger.tsx
- packages/react-tree-grid/src/components/TreeGridRowTrigger/index.ts
- packages/react-tree-grid/src/index.ts
- packages/react-tree-grid/stories/Calls.stories.tsx
- packages/react-tree-grid/stories/LiveMeetingsList.stories.tsx
Creates a Trigger component to simplify use cases where a trigger to open/close the current row is required
1. Creates `TreeGridRowTrigger` component
2. Adds usage of it in `Calls` example
3. Bugfix to ensure SVGElements won't be ignored on a click https://github.com/microsoft/fluentui-contrib/pull/364#discussion_r2053768358
> feature(react-tree-grid): TreeGridRowTrigger component

- change/@fluentui-contrib-houdini-utils-11b65663-b7d6-4a80-8b7a-ef970d56300d.json
- packages/houdini-utils/src/paint/fallback/anims/play.ts
For the fallback Safari implementation we rely on the vendor-specific, undocumented `-webkit-canvas()` CSS function. This function takes an ID but not a CSS ID. In other words:
```css
/* ⛔ nope */
background-image: -webkit-canvas(#css-id-selector-will-not-work);
/* ✅ yep */
background-image: -webkit-canvas(id-selector-will-work);
```
> Fix Safari bug in Houdini utils

- change/@fluentui-contrib-react-tree-grid-29d75719-930c-4f4a-b9f7-f5593f2734dc.json
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.types.ts
Types generated at react-tree-grid v0.1.4:
```tsx
/** @jsxRuntime classic */
/** @jsx createElement */
/** @jsxFrag Fragment */
import { Fragment } from '@fluentui/react-jsx-runtime';
import * as React from 'react';
export declare const TreeGridRow: React.ForwardRefExoticComponent<Omit<import("./TreeGridRow.types").TreeGridRowSlots, "root"> & Omit<{
as?: "div" | undefined;
} & Omit<React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "ref"> & {
ref?: ((instance: HTMLDivElement | null) => void | React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | React.RefObject<HTMLDivElement> | null | undefined;
} & {
children?: React.ReactNode | …
```
> bugfix(react-tree-grid): slot type breaks when using typeof exotic component with react v17

- change/@fluentui-contrib-react-resize-handle-4b03fba0-74e7-4937-a468-cde9594620c2.json
- packages/react-resize-handle/src/hooks/useResizeHandle.component-browser-spec.tsx
- packages/react-resize-handle/src/hooks/useResizeHandle.ts
Updates for #375.
We actually cannot allow CSS variable to exceed `clamp()` and `width` (i.e. `clamp()`) definition could be changed based on, for example, media queries and will cause unexpected jumps. This makes aligned it with the previous implementation except emitting falsy `onChange` events.
> fix(resize-handle): updates for #375

- change/@fluentui-contrib-react-resize-handle-52670819-1a5d-4c12-96f1-836c93979a33.json
- packages/react-resize-handle/src/hooks/useResizeHandle.component-browser-spec.tsx
- packages/react-resize-handle/src/hooks/useResizeHandle.ts
- packages/react-resize-handle/src/hooks/useResizeHandleExample.component-browser-spec.tsx
- packages/react-resize-handle/stories/Default.stories.tsx
As we don't call `onChange()` without actual changes in DOM (#375), there is no way to know that there is a resize attempt outside of CSS clamp range. This PR adds `onChangeRejected()` callback:
New test cases added, the story is updated.
> feat(resize-handle): add onChangeRejected() callback

- change/@fluentui-contrib-react-virtualizer-c65aff71-b424-40d9-9d28-673e52c69f77.json
- packages/react-virtualizer/src/hooks/useDynamicVirtualizerMeasure.ts
Virtualizer would occasionally get stuck at the end due to it trying to optimize the required length, however we can simply enable Virtualizer length to go beyond the end item and stay there.
Once we reach the end, no optimizations needed until index change requires a recalculation.
> Fix: Prevent dynamic virtualizer getting stuck at the end

- .github/CODEOWNERS
This pull request makes a small update to the `CODEOWNERS` file, adding an additional team as co-owner for the `packages/react-virtualizer` package. This change ensures that both the `@microsoft/xc-uxe` and `@microsoft/cxe-prg` teams are now responsible for this package.
> chore: add cxe-prg to react-virtualizer codeowners

- change/@fluentui-contrib-react-virtualizer-a47074a8-2c13-4436-8bda-ba0941b109ad.json
- packages/react-virtualizer/src/components/Virtualizer/useVirtualizer.ts
- packages/react-virtualizer/src/hooks/useDynamicVirtualizerMeasure.ts
Previously, we had a safety check to ensure we don't re-render if the virtualizer is at the 'end' of the array.
While this check is important, if the number of items rendered is modified, we do want to ensure it recalculates the index based on the new array length.
This check should ensure that when items are removed we recalc where nessecary at the BASE virtualizer hook (similar to what we added for the dynamic virtualizer check).
> fix (react-virtualizer): Ensure base virtualizer hook recalcs array if numItems change at end
