- change/@fluentui-contrib-react-chat-7f9c60e6-1272-4d06-9859-54d3edf4714d.json
- packages/nx-plugin/package.json
- packages/nx-plugin/src/executors/build/executor.ts
- packages/react-chat/package.json
All packages are built with @swc/helpers and tslib. Add these dependencies to every package.json in build output
> chore: Add build dependencies to packages

- .github/workflows/docs.yml
Adds a new workflow `docs.yml` to publish storybooks to github pages
> chore: workflow to publish storybooks to github pages

- .github/workflows/CODEOWNERS
Adds a CODEOWNERS file with owners to the current packages in the repo
> chore: Setup codeowners in repository

- packages/nx-plugin/src/generators/library/generator.spec.ts
- tsconfig.base.json
> chore: enable "strict" for TS

- .github/CODEOWNERS
- .github/workflows/ci.yml
- .prettierignore
- CONTRIBUTING.md
Adds a check for code formatting on CI powered by [nx format](https://nx.dev/packages/nx/documents/format-check). Also adds documentation how to run the formatter locally to contributing docs
> chore: Add formatting check to CI

- README.md
> docs: update README to include react-shadow

- packages/react-data-grid-react-window/.storybook/main.ts
> chore: Enable storybook code for data grid

- change/@fluentui-contrib-react-data-grid-react-window-1c20fe1d-9b5b-4260-b1ad-22d0526fc8dd.json
- packages/react-data-grid-react-window/src/components/DataGridBody/DataGridBody.types.ts
- packages/react-data-grid-react-window/src/components/DataGridBody/useDataGridBody.tsx
pr in fluentui has been merged before @fluentui/react-data-grid-react-window been deprecated: https://github.com/microsoft/fluentui/pull/28205
> Added index in DataGridBody RowRenderer

- package.json
- packages/nx-plugin/src/generators/library/generator.spec.ts
- packages/react-data-grid-react-window/README.md
- yarn.lock
Bump react-components version to 9.30.0
> minor: Bump react-components version to 9.30.0

- change/@fluentui-contrib-react-headless-provider-4bbc80af-6c3f-4517-a756-ea86913c5153.json
- packages/react-headless-provider/package.json
Oops, noticed that the package have not been released, time to release it :)
> chore: publish @fluentui-contrib/react-headless-provider

- change/@fluentui-contrib-react-chat-813d6ccd-7207-480d-98e1-b4a41eaac38b.json
- change/@fluentui-contrib-react-data-grid-react-window-76605a09-9803-4e18-9382-60cacc02849e.json
- change/@fluentui-contrib-react-shadow-8d19b095-4de6-429d-b5b9-0dd8e289793a.json
- change/@fluentui-contrib-stylelint-plugin-a04825c5-30cc-4e1e-b4cf-04bb045938d0.json
- packages/nx-plugin/src/executors/build/executor.ts
Fixes the issue wrong `exports.types` field:
Should be `./src/index.d.ts`.
> fix: fix "exports.types" field

- .github/workflows/ci.yml
- yarn.lock
Runs [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) in CI and adds a check for unstaged changes
> chore: Deduplicate yarn.lock and check for unstaged changes

- change/@fluentui-contrib-react-data-grid-react-window-grid-aa3d16d9-de32-47c2-89a0-905c22f1beb0.json
- packages/react-data-grid-react-window-grid/package.json
Initial release on @fluentui-contrib/react-data-grid-react-window-grid
> feat: Initial release on @fluentui-contrib/react-data-grid-react-window-grid

- packages/react-tree-grid/.eslintrc.json
- packages/react-tree-grid/.storybook/main.ts
- packages/react-tree-grid/.storybook/preview.tsx
- packages/react-tree-grid/.storybook/tsconfig.json
- packages/react-tree-grid/.swcrc
- packages/react-tree-grid/README.md
- packages/react-tree-grid/jest.config.ts
- packages/react-tree-grid/package.json
- packages/react-tree-grid/project.json
- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.tsx
- packages/react-tree-grid/src/components/TreeGrid/index.ts
- packages/react-tree-grid/src/components/TreeGridCell/TreeGridCell.tsx
- packages/react-tree-grid/src/components/TreeGridCell/index.ts
- packages/react-tree-grid/src/components/TreeGridRow/TreeGridRow.tsx
- packages/react-tree-grid/src/components/TreeGridRow/index.ts
- packages/react-tree-grid/src/index.ts
- packages/react-tree-grid/stories/TreeGridVariantB.stories.tsx
- packages/react-tree-grid/stories/VariantB/TreeGridUtils.ts
- packages/react-tree-grid/stories/VariantB/TreeGridWithEnterInputsRenderer.tsx
- packages/react-tree-grid/stories/VariantB/index.ts
- packages/react-tree-grid/stories/VariantB/useAdamTableInteractive2Navigation.ts
- packages/react-tree-grid/stories/index.stories.tsx
- packages/react-tree-grid/tsconfig.json
- packages/react-tree-grid/tsconfig.lib.json
- packages/react-tree-grid/tsconfig.spec.json
- tsconfig.base.json
This is basically a copy paste from the example provided by @adamsamec  at https://github.com/microsoft/fluentui/pull/29780
> chore(react-tree-grid): scaffold package

- packages/react-draggable-dialog/.storybook/main.ts
- packages/react-draggable-dialog/.storybook/preview.tsx
- packages/react-draggable-dialog/.storybook/tsconfig.json
- packages/react-draggable-dialog/project.json
- packages/react-draggable-dialog/tsconfig.json
- packages/react-draggable-dialog/tsconfig.lib.json
> feat(react-draggable-dialog): add missing storybook config

- .github/CODEOWNERS
adding access rights for fluent v-build related domains in order to streamline reviewing process/ownership
> chore: add v-build to codeowners

- .github/workflows/ci-change.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- CONTRIBUTING.md
- azure-pipelines.yml
- package.json
align with core fluent and also to use LTS
> chore: bump to node 18

- packages/react-tree-grid/package.json
- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.tsx
- packages/react-tree-grid/src/components/TreeGridInteraction/TreeGridInteraction.tsx
- packages/react-tree-grid/src/components/TreeGridInteraction/TreeGridInteraction.types.ts
- packages/react-tree-grid/src/components/TreeGridInteraction/index.ts
- packages/react-tree-grid/src/index.ts
- packages/react-tree-grid/stories/Interaction.stories.tsx
- packages/react-tree-grid/stories/index.stories.tsx
1. Adds `TreeGridInteraction` component to ensure complex components interactions behaviour according to @adamsamec  specs https://github.com/microsoft/fluentui/pull/29780
> feature(react-tree-grid): TreeGridInteraction component

- packages/nx-plugin/src/generators/playwright-component-configuration/generator.spec.ts
- packages/nx-plugin/src/generators/playwright-component-configuration/generator.ts
> fix(nx-plugin): generate valid playwright executor target options

- packages/react-tree-grid/.eslintrc.json
- packages/react-tree-grid/jest.config.ts
- packages/react-tree-grid/playwright.config.ts
- packages/react-tree-grid/playwright/index.html
- packages/react-tree-grid/playwright/index.tsx
- packages/react-tree-grid/project.json
- packages/react-tree-grid/src/components/TreeGrid/TreeGrid.spec.tsx
- packages/react-tree-grid/src/components/TreeGrid/TreeGridExample.spec.tsx
1. adds playwright component test configuration
2. adds playwright test for TreeGrid keyboard/click behaviours
> chore(react-tree-grid): adds playwright component tests

- change/@fluentui-contrib-houdini-utils-23df6302-2358-46d8-99e6-bad753b21126.json
- packages/houdini-utils/src/index.ts
> fix: re-export addModule

- .github/CODEOWNERS
- package.json
- packages/react-themeless-provider/.babelrc
- packages/react-themeless-provider/.eslintrc.json
- packages/react-themeless-provider/.storybook/main.ts
- packages/react-themeless-provider/.storybook/preview.tsx
- packages/react-themeless-provider/.storybook/tsconfig.json
- packages/react-themeless-provider/.swcrc
- packages/react-themeless-provider/README.md
- packages/react-themeless-provider/jest.config.ts
- packages/react-themeless-provider/package.json
- packages/react-themeless-provider/project.json
- packages/react-themeless-provider/src/components/ThemelessFluentProvider/ThemelessFluentProvider.styles.ts
- packages/react-themeless-provider/src/components/ThemelessFluentProvider/ThemelessFluentProvider.test.tsx
- packages/react-themeless-provider/src/components/ThemelessFluentProvider/ThemelessFluentProvider.tsx
- packages/react-themeless-provider/src/components/ThemelessFluentProvider/index.ts
- packages/react-themeless-provider/src/index.ts
- packages/react-themeless-provider/stories/ThemelessFluentProvider/Default.stories.tsx
- packages/react-themeless-provider/stories/ThemelessFluentProvider/index.stories.tsx
- packages/react-themeless-provider/tsconfig.json
- packages/react-themeless-provider/tsconfig.lib.json
- packages/react-themeless-provider/tsconfig.spec.json
- tsconfig.base.json
Scaffolds a `ThemelessFluentProvider` component per [FluentUI#30241](https://github.com/microsoft/fluentui/issues/30241)
Previously this was in #145 but there were issues with the generator scripts so I spun up a new PR.
> chore: scaffold react-themeless-provider package

- change/@fluentui-contrib-react-data-grid-react-window-grid-4bc3677a-03e4-4ff1-9ed2-ab0f9bb4d5d2.json
- packages/react-data-grid-react-window-grid/src/components/DataGridBody/useDataGridBody.tsx
Fix columns update not trigger rerender cell
> patch(react-data-grid-react-window-grid): Fix columns update not trigger rerender

- .github/CODEOWNERS
- CONTRIBUTING.md
> docs: improve contribution guidelines when creating new packages

- .github/workflows/ci.yml
- change/fluentui-contrib-e0f9df68-b86b-4cc8-9fd2-a18226c70fdb.json
- change/fluentui-contrib-e822b249-aa15-4cb7-979e-467b1a976aa2.json
- package.json
- project.json
- tools/scripts/verify-repo-integrity.mjs
1. Removes invalid changefiles introduced
- https://github.com/microsoft/fluentui-contrib/pull/143/files#diff-935baad70042ef84471b919f884a2f7b73ef42ddfd003dc059c50310b819bebe
- https://github.com/microsoft/fluentui-contrib/pull/149/files#diff-0862bad8eb7dca9166db074d664922457daf1349e8084c75c1e29f93b6ce097a 
- <img width="1297" alt="image" src="https://github.com/microsoft/fluentui-contrib/assets/1223799/da420e99-5e32-4ba2-adf8-45b54c6de448">
2. introduces verify-integrity target within root repo which will be executed only if root repo files are affected
> feat: implement verify integrity check

- .github/workflows/ci-change.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- azure-pipelines.yml
- package.json
- yarn.lock
see pr title
---
Follows:https://github.com/microsoft/fluentui/pull/31495
> chore: migrate repo to node 20

- packages/azure-theme/README.md
> Azure theme readme

- packages/react-resize-handle/.eslintrc.json
- packages/react-resize-handle/playwright.config.ts
- packages/react-resize-handle/playwright/index.html
- packages/react-resize-handle/playwright/index.tsx
- packages/react-resize-handle/project.json
Inits playwright via the generator.
> chore(resize-handle): init playwright

- change/@fluentui-contrib-variant-theme-fbc498b5-3b02-4a4c-817e-462a124bcab6.json
- packages/variant-theme/package.json
remove private so the package can be actually released
follows https://github.com/microsoft/fluentui-contrib/pull/240
> feat(variant-theme): prepare initial release

- change/@fluentui-contrib-react-interactive-tab-a981d48f-c6af-490c-b60a-94e87d6a6a10.json
- packages/react-interactive-tab/package.json
- remove `private: true` so the package can be released
- generate change file in order to trigger first release
> feat(react-interactive-tab): prepare initial release

- change/@fluentui-contrib-react-keytips-6c388a16-92f8-4352-a0e6-37f7bdd0eb14.json
- packages/react-keytips/src/components/Keytips/Keytips.component-browser-spec.tsx
- packages/react-keytips/src/components/Keytips/Keytips.test.tsx
- packages/react-keytips/src/components/Keytips/Keytips.types.ts
- packages/react-keytips/src/components/Keytips/useKeytips.tsx
- packages/react-keytips/src/docs/MIGRATION.md
- packages/react-keytips/src/hooks/useHotkeys.ts
Feature was requested earlier for v8: https://github.com/microsoft/fluentui/issues/31499.
> feat(react-keytips): add invokeEvent prop

- .github/workflows/ci.yml
- package.json
- packages/nx-plugin/src/executors/playwright/executor.ts
- packages/nx-plugin/src/generators/playwright-component-configuration/files/playwright.config.ts.template
- packages/react-draggable-dialog/playwright.config.ts
- packages/react-interactive-tab/playwright.config.ts
- packages/react-keytips/playwright.config.ts
- packages/react-resize-handle/playwright.config.ts
- packages/react-tree-grid/playwright.config.ts
- packages/variant-theme/playwright.config.ts
- yarn.lock
replaces https://github.com/microsoft/fluentui-contrib/pull/276
> chore: update playwright to 1.49.1 and resolve CT port clashes on ci/local

- change/@fluentui-contrib-react-keytips-c341fb03-d4b1-4cd3-9f39-851d2246ea52.json
- packages/react-keytips/src/components/Keytips/Keytips.component-browser-spec.tsx
- packages/react-keytips/src/components/Keytips/KeytipsExamples.component-browser-spec.tsx
- packages/react-keytips/src/hooks/useTree.test.ts
- packages/react-keytips/stories/Shortcuts.md
A few tests for Keytip shortcuts.
> test(react-keytips): add tests for shortcut

- change/@fluentui-contrib-react-keytips-c341fb03-d4b1-4cd3-9f39-851d2246ea52.json
- change/@fluentui-contrib-stylelint-plugin-79aafcea-5765-4f2c-af35-91dba0eb16de.json
- change/@fluentui-contrib-stylelint-plugin-dd35e5e0-02c3-4054-8324-761193e501d8.json
- packages/react-keytips/CHANGELOG.json
- packages/stylelint-plugin/CHANGELOG.json
- packages/stylelint-plugin/CHANGELOG.md
- packages/stylelint-plugin/package.json
release pipeline failed (packages have been released to npm successfully) when pushing updates back to origin. 
This is a manual version bump in order to sync changes from CI to master with npm.
> ran via `yarn beachball bump -b upstream/master --access public --no-fetch --no-publish --no-push --no-git-tags --verbose`
> release: applying package updates

- azure-pipelines.yml
unfortunately the ADO app connection doesn't work for pushes to GH
Reverts microsoft/fluentui-contrib#289
> revert: "ci: remove use of PAT on release pipeline"

- packages/teams-components/src/index.ts
- packages/teams-components/src/strictStyles/STRICT_SYMBOL.ts
- packages/teams-components/src/strictStyles/createStrictClass.test.ts
- packages/teams-components/src/strictStyles/createStrictClass.ts
- packages/teams-components/src/strictStyles/index.ts
- packages/teams-components/src/strictStyles/makeStrictStyles.production.test.ts
- packages/teams-components/src/strictStyles/makeStrictStyles.test.ts
- packages/teams-components/src/strictStyles/makeStrictStyles.ts
- packages/teams-components/src/strictStyles/mergeStrictClasses.production.test.ts
- packages/teams-components/src/strictStyles/mergeStrictClasses.test.ts
- packages/teams-components/src/strictStyles/mergeStrictClasses.ts
- packages/teams-components/src/strictStyles/types.ts
- packages/teams-components/src/strictStyles/validateStrictClasses.test.ts
- packages/teams-components/src/strictStyles/validateStrictClasses.ts
Adds `makeStrictStyles` and `mergeStrictClasses` implementations
> feat: adds strict styles implementation

- change/@fluentui-contrib-react-keytips-a4582e5f-6bff-4c22-9227-f3ec97e68845.json
- packages/react-keytips/src/components/Keytips/renderKeytips.tsx
- packages/react-keytips/src/hooks/useHotkeys/useHotkeys.ts
- packages/react-keytips/stories/Overflow/OverflowMenu.tsx
fixing reported issues after bug bush (vol 2): 11, 12, 13
> fix(react-keytips): reported issues after bug bash vol 2

- .github/dependabot.yml
- .github/workflows/ci.yml
follows https://github.com/microsoft/fluentui/pull/34004
> ci: pin 3rd party GHA version to SHA

- .github/dependabot.yml
resolve https://github.com/microsoft/fluentui-contrib/runs/38891681773
> ci: fix invalid dependabot config for schedule

- change/@fluentui-contrib-teams-components-476759fc-4510-4a68-881a-3e1078ea0d96.json
- packages/teams-components/package.json
Remove `private: true` from the matching `package.json`.
> chore: prepare to publish @fluentui-contrib/teams-components

- .github/CODEOWNERS
Created a new team for azure design engineering since the admin/only other member is on extended leave.
> Updated codeowners for azure-theme package
